service: ko-sports-backend
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    API_VERSION: ${env:API_VERSION, '0.0.0-local'}

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  individually: true

custom:
  esbuild:
    sourcemap: true
    bundle: true
    minify: false
    plugins: esbuildPlugin.cjs
    packager: "yarn"
    loader:
      .node: "copy"
    watch:
      pattern: ["src/**/*.ts"]
  serverless-offline:
    useInProcess: true

functions:
  function1:
    handler: src/index.handler
    events:
      - http:
          path: /test
          method: get
