service: ko-sports-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  environment:
    API_VERSION: ${env:API_VERSION}

plugins:
  - serverless-offline

functions:
  function1:
    handler: index.handler
