# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rahulp959
service: ko-sports-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    API_VERSION: ${env:API_VERSION, '0.0.0-local'}

plugins:
  - serverless-offline
  - serverless-domain-manager

package:
  individually: true

build:
  esbuild:
    sourcemap: true
    bundle: true
    minify: false
    target: node20
    platform: node
    plugins: [esbuildPlugin.cjs]
    packager: "npm"
    loader:
      .node: "copy"
    watch:
      pattern: ["src/**/*.ts"]
    external: ["@sentry/profiling-node"]

custom:
  customDomain:
    domainName: ko-sports-api.rbcdigital.tech
    stage: dev
    certificateName: ko-sports-api.rbcdigital.tech
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: REGIONAL
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: true
  serverless-offline:
    useInProcess: true
    httpPort: 4000

functions:
  authorizer:
    handler: src/auth/index.handler
    environment:
      JWKS_URI: ${env:JWKS_URI}
      AUDIENCE: ${env:AUDIENCE}
      TOKEN_ISSUER: ${env:TOKEN_ISSUER}
  healthCheck:
    handler: src/healthCheck/index.handler
    events:
      - http:
          path: /health
          method: get
  function1:
    handler: src/index.handler
    events:
      - http:
          path: /test
          method: get
          authorizer: authorizer
  checkProfile:
    handler: src/routes/auth/checkProfile/index.handler
    events:
      - http:
          path: /auth/check-profile
          method: get
          authorizer: authorizer
  createProfile:
    handler: src/routes/auth/createProfile/index.handler
    events:
      - http:
          path: /auth/create-profile
          method: post
          authorizer: authorizer
  updateProfile:
    handler: src/routes/auth/updateProfile/index.handler
    events:
      - http:
          path: /auth/update-profile
          method: put
          authorizer: authorizer
