service: ko-sports-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  environment:
    API_VERSION: ${env:API_VERSION, '0.0.0-local'}

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: false
    packager: "yarn"
    external:
      - "@sentry/profiling-node"
    packagerOptions:
      scripts:
        - "yarn add @sentry/profiling-node"
      ignoreLockfile: true
    watch:
      pattern: ["src/**/*.ts"]
  serverless-offline:
    useInProcess: true

functions:
  function1:
    handler: src/index.handler
    events:
      - http:
          path: /test
          method: get
