name: Deploy

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - name: Setup Node 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: KoSportsDeploy
          aws-region: eu-west-1

      - run: yarn install --immutable

      - name: Set API Version
        run: echo "API_VERSION=$(npm pkg get version | xargs echo)-$GITHUB_SHA" >> $GITHUB_ENV

      - run: yarn deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          TOKEN_ISSUER: ${{ secrets.TOKEN_ISSUER }}
          AUDIENCE: ${{ secrets.AUDIENCE }}
          JWKS_URI: ${{ secrets.JWKS_URI }}
