name: Deploy

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 20.x

      - name: Install PNPM Dependencies
        run: pnpm install

      - name: Test
        run: pnpm run test

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: KoSportsDeploy
          aws-region: eu-west-1

      - run: pnpm install

      - name: Set API Version
        run: echo "API_VERSION=$(npm pkg get version | xargs echo)-$GITHUB_SHA" >> $GITHUB_ENV

      - run: pnpm run deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          TOKEN_ISSUER: ${{ secrets.TOKEN_ISSUER }}
          AUDIENCE: ${{ secrets.AUDIENCE }}
          JWKS_URI: ${{ secrets.JWKS_URI }}
